#!/usr/bin/env bash

# Timetracker action for todo.txt
# Gives timetracker stats for a project
# (C) 2012 Paul Mansfield
# License:  GPL, http://www.gnu.org/copyleft/gpl.html

usage() {
	echo "    $(basename "${0}") on|off|list|archive|unarchive|stats|archivedstats|statsall [PROJECT]"
	echo "      Track time spent on a project."
}

die () {
  [[ -f "${TODO_TMP_FILE}" ]] && rm -rf "${TODO_TMP_FILE}"
	exit 1
}

ttprep() {
	# Make directories that may be needed
	if [ ! -d "${TODO_DIR}/tt/${PRE}/" ]; then
		mkdir -p "${TODO_DIR}/tt/${PRE}"
	fi
	if [ ! -d "${TODO_DIR}/tt/${PRE}/archive" ]; then
		mkdir -p "${TODO_DIR}/tt/${PRE}/archive"
	fi
}

tttests () {
	# If we are getting stats, allow blank project, else error
	if [[ -z "${1}" ]]; then
		if [[ $(echo "${action}" | grep -c 'list\|stats') -eq 1 ]]; then
			ALL=1
		# elif [[ "$(echo "${action}" | grep -c 'list\|stats')" -eq 0 ]]; then
		# 	usage
		# 	echo "      No project given"
		# 	die
		fi
	else
		# Remove + from project
		project="${1/#+/}"
		ALL=0
	fi
}

# Usage for todo.sh help or remove action
# Remove todo.txt action name
if [[ "${2}" =~ (usage|help|--help) ]]; then
	usage
	die
elif [[ "${1}" = "$(basename "$0")" ]]; then
  shift
  action=$1
  shift
fi

# Setup some variables
PRE=$(basename "${TODO_FILE}" | sed 's/.txt$//g')

# Run our prep and tests
ttprep
tttests "$@"

# Setup some variables
# Find current and archived projects
CURRENT=$(find "${TODO_DIR}/tt/${PRE}/" -maxdepth 1 -name "*.tt" | awk -F / '{print $NF}' | sed 's/\.tt$//' | sort)
ARCHIVED=$(find "${TODO_DIR}/tt/${PRE}/archive/" -maxdepth 1 -name "*.tt" | awk -F / '{print $NF}' | sed 's/\.tt$//' | sort)
# Current and archive file location for PROJECT
FILE="${TODO_DIR}/tt/${PRE}/${project}.tt"
ARCHIVE="${TODO_DIR}/tt/${PRE}/archive/${project}.tt"

# Human style timings from seconds since epoc.
# Find days, remove that from total,
# find hours, remove that from total,
# find minutes, remove that from total,
# display seconds.
tthuman () {
	TOTAL=$1
	RUNNING=$2
	DAYS=$((TOTAL / 86400))
	if [[ "${DAYS}" -gt 0 ]]; then
		TEXTDAYS="${DAYS} days "
	else
		TEXTDAYS=""
	fi
	# shellcheck disable=SC2034,SC2035
	REMOVEDAYS=$((TOTAL - DAYS * 86400))
	HOURS=$((REMOVEDAYS / 3600))
	if [ "${HOURS}" -gt 0 ]; then
		TEXTHOURS="${HOURS} hours "
	else
		TEXTHOURS=""
	fi
	# shellcheck disable=SC2034,SC2035
	REMOVEHOURS=$((REMOVEDAYS - HOURS * 3600))
	MINUTES=$((REMOVEHOURS / 60))
	if [[ "${MINUTES}" -gt 0 ]]; then
		TEXTMINUTES="${MINUTES} minutes "
	else
		TEXTMINUTES=""
	fi
	# shellcheck disable=SC2034,SC2035
		SECONDS=$((REMOVEHOURS - MINUTES * 60))
	if [[ "${SECONDS}" -gt 0 ]]; then
		TEXTSECONDS="${SECONDS} seconds "
	else
		TEXTSECONDS=""
	fi
}

# Archive the project tt file
ttarchive() {
	project="${1/#+/}"
  localUsage () {
    echo "    $(basename "$0") ${action} [PROJECT]"
    echo "      Archive current projects"
	}
	if [[ -z "${project}" ]]; then
		localUsage
		echo "      No project given"
		die
	elif [[ "${project}" = "usage" ]]; then
		localUsage
		exit
	elif [ -f "${FILE}" ]; then
		if [ "$(tail -1 "${FILE}" | grep -c :)" -eq 0 ]; then
			echo "$(cat "${FILE}"):$(date +%s)" >> "${FILE}"
			rm "${FILE}" 
			echo "Setting project ${project} as finished now and archiving"
		else
			mv "${FILE}" "${TODO_DIR}/tt/${PRE}/archive/"
			echo "Archived ${project}"
		fi
	else
		localUsage
		echo "      Project ${project} does not exist"
		die
	fi
}

ttunarchive () {
	project="${1/#+/}"
  localUsage () {
    echo "    $(basename "$0") ${action} [PROJECT]"
    echo "      Unarchive projects"
	}
	if [[ -z "${project}" ]]; then
		localUsage
		echo "      No project given"
		die
	elif [[ "${project}" = "usage" ]]; then
		localUsage
		exit
	elif [ -f "${ARCHIVE}" ]; then
		mv "${ARCHIVE}" "${FILE}"
		echo "Project ${project} unarchived"
	else
		localUsage
		echo "      Project ${project} not archived"
		die
	fi
}

ttlist () {
  localUsage () {
    echo "    $(basename "$0") ${action}"
    echo "      Show list of current and archived projects"
	}
	if [[ "${project}" = "usage" ]]; then
		localUsage
		exit
	fi
	if [ "${#CURRENT}" -gt 0 ] || [ "${#ARCHIVED}" -gt 0 ]; then
		echo "Projects being time tracked"
		echo "==========================="
		if [ ${#CURRENT} -gt 0 ]; then
			echo "Current"
			echo "-------"
			echo "$CURRENT"
			echo ""
		fi
		if [ ${#ARCHIVED} -gt 0 ]; then
			echo "Archived"
			echo "--------"
			echo "$ARCHIVED"
			echo ""
		fi
	else
		localUsage
		echo "      No files to list"
		die
	fi
}

ttsimplelist () {
    echo "${CURRENT}"
}

ttsimplearchivedlist () {
    echo "${ARCHIVED}"
}

ttsimplelistall () {
    echo "${CURRENT}"
		echo "${ARCHIVED}"
}

tton() {
	project="${1/#+/}"
  localUsage () {
    echo "    $(basename "$0") ${action} [PROJECT]"
    echo "      Start tracking time in PROJECT"
	}
	_start () {
		# if tt file doesn't exist start
		if ! [[ -f "${FILE}" ]]; then
			date +"%s" >> "${FILE}"
			echo "${1}"
			exit
		fi
		# If project file exists and if our last line has only two fields, then add time stamp
		if [ "$(tail -1 "${FILE}" | grep -c :)" -eq 1 ] ; then
			date +"%s" >> "${FILE}"
			echo "${1}"
			exit
		# Else the timer is still active
		else
			localUsage
			echo "      Project ${project} is still active, cannot turn on the clock"
			die
		fi
	}
	if [[ "${project}" = "usage" ]]; then
		localUsage
		die
	# if no project error
	elif [[ -z "${project}" ]]; then
		localUsage
		echo "      No project given"
		die
	# if project is in todo.txt
	elif [[ $(grep -c "+${project}" "${TODO_FILE}") -gt 0 ]]; then
		# if project tt file exists
		if [[ -f "${FILE}" ]]; then
			_start "Starting clock on ${project}"
		# if project tt archivefile exists, ask to unarchive and then start
		elif [[ -f "${ARCHIVE}" ]]; then
			echo "Project ${project} is archived, unarchive?"
			read -r -n1 -p "(y/n)"
			if [[ "${REPLY}" = [yY] ]]; then
				mv "${ARCHIVE}" "${FILE}" 
				_start "Unarchiving and starting clock on ${project}"
			else
				echo "Not unarchiving"
				die
			fi
		fi
		# if no tt file exits, start one
		_start "Starting clock on ${project}"
	# if project is not in todo.txt
	else
		localUsage
		echo "      Project ${project} is not in todo.txt"
		die
	fi
}


ttoff() {
	project="${1/#+/}"
  localUsage () {
    echo "    $(basename "$0") ${action} [PROJECT]"
    echo "      Stop tracking time in PROJECT"
	}
	_stop () {
		# Remove the state and set File location
		STATE=$1; shift
		if [[ "${STATE}" = "live" ]]; then
			FILE="${TODO_DIR}/tt/${PRE}/${project}"
		elif [[ "${STATE}" = "archived" ]]; then
			FILE="${TODO_DIR}/tt/${PRE}/archive/${project}"
		fi
		# Get start from last line of project tt file
		START=$(tail -1 "${FILE}.tt")
		# Current time
		END="$(date +"%s")"
		# Print all but last line, then start and end into temp file
		head -n -1 "${FILE}.tt"; echo "${START}:${END}" > "${FILE}.tmp"
		mv "${FILE}.tmp" "${FILE}.tt"
		echo "${1}"
		exit
	}

	if [[ "${project}" = "usage" ]]; then
		localUsage
		die
	elif [[ -z "${project}" ]]; then
		localUsage
		echo "      No project given"
		die
	# if project has a tt file started
	elif [[ -f "${FILE}" ]] && [[ "$(tail -1 "${FILE}" | grep -c :)" -eq 0 ]] ; then
		_stop live "Stopping clock on ${project}"
	# if project has an archived tt file started
	elif [[ -f "${ARCHIVE}" ]] && [[ "$(tail -1 "${ARCHIVE}" | grep -c :)" -eq 0 ]] ; then
		_stop archived "Stopping clock on ${project} which is archived"
	# if project has neither a started tt file nor started archive file
	elif [[ (-f "${FILE}" && "$(tail -1 "${FILE}" | grep -c :)" -eq 1 ) ]] && [[ (-f "${ARCHIVE}" && "$(tail -1 "${ARCHIVE}" | grep -c :)" -eq 1) ]]; then
		localUsage
		echo "      Project ${project} is not active"
		die
	# if project is not in todo.txt file
	elif [[ "$(grep -c "${project}" "${TODO_FILE}")" -eq 0  ]]; then
		localUsage
		echo "      Project ${project} does not exist in todo.txt"
		die
	# if project has no tt file nor archive file
	elif [[ ! -f "${FILE}"  ]] && [[ ! -f "${ARCHIVE}" ]]; then
		localUsage
		echo "      No sign of tt file for project ${project}"
		die
	fi
}

# Show the stats for the project
ttstats (){
  localUsage () {
    echo "    $(basename "$0") ${action} [PROJECT]"
    echo "      Show stats on PROJECT"
	}
	_stats() {
		project="${1/#+/}"
		# if we have a tt project file show it, else error out
		if [ -f "${TODO_DIR}/tt/${PRE}/${project}.tt" ]; then
			# Find total and show if still running or complete
			if [ "$(tail -1 "${TODO_DIR}/tt/${PRE}/${project}.tt" | grep -c :)" -eq 0 ]; then
				TOTAL=$(echo "$(cat "${TODO_DIR}/tt/${PRE}/${project}.tt"):$(date +%s)" |awk -F ':' '{print $2 - $1}' | awk '{ sum+=$1} END {print sum}')
				RUNNING=0
			else
				TOTAL=$(awk -F ':' '{print $2 - $1}' "${TODO_DIR}/tt/${PRE}/${project}.tt" | awk '{ sum+=$1} END {print sum}')
				RUNNING=-1
			fi
			# Print out the stats
			tthuman "${TOTAL}" "${RUNNING}"
			echo "Stats for Project: ${project}"
			# Double underline title
			echo "Stats for Project: ${project}"| sed 's/./=/g'
			if [[ ${RUNNING} -eq 0 ]]; then
				echo "Timer still running for ${project}"
			fi
			echo "${TEXTDAYS}${TEXTHOURS}${TEXTMINUTES}${TEXTSECONDS}"
		else
			localUsage
			echo "      No current timetracker projects"
			die
		fi
	}
	if [[ "${project}" = "usage" ]]; then
		localUsage
		exit
	# If no project was set, show all projects stats
	elif [ ${ALL} -eq 1 ]; then
		# Find all current tt project files
		cd "${TODO_DIR}/tt/${PRE}/" || exit 1
		for project in *.tt; do
			# Remove .tt
			project="${project/%???/}"
			_stats "${project}"
		done
	else
		# Find all projects given on command line
		# shellcheck disable=SC2068
		for project in $@; do
			# Remove .tt
			project="${project/#+/}"
			_stats "${project}"
		done
	fi
}

ttarchivedstats () {
	project="${1/#+/}"
	localUsage () {
    echo "    $(basename "$0") ${action} [PROJECT]"
    echo "      Show stats on archived PROJECT"
	}
	_archivedstats () {
		# if we have an archived tt project file show it, else error out
		if [ -f "${TODO_DIR}/tt/${PRE}/archive/${project}.tt" ]; then
			# Find total and show if still running or complete
			if [ "$(tail -1 "${TODO_DIR}/tt/${PRE}/archive/${project}.tt" | grep -c :)" -eq 0 ]; then
				TOTAL=$(echo "$(cat "${TODO_DIR}/tt/${PRE}/archive/${project}.tt"):$(date +%s)" |awk -F ':' '{print $2 - $1}' | awk '{ sum+=$1} END {print sum}')
				RUNNING=1
			else
				TOTAL=$(awk -F ':' '{print $2 - $1}' "${TODO_DIR}/tt/${PRE}/archive/${project}.tt" | awk '{ sum+=$1} END {print sum}')
				RUNNING=0
			fi
			# Print out the stats
			tthuman "${TOTAL}" "${RUNNING}"
			echo "Stats for archived Project: ${project}"
			# Double underline title
			echo "Stats for archived Project: ${project}"| sed 's/./=/g'
			if [[ ${RUNNING} -eq 1 ]]; then
				echo "Timer still running for ${project}"
			fi
			echo "${TEXTDAYS}${TEXTHOURS}${TEXTMINUTES}${TEXTSECONDS}"
		else
			localUsage
			echo "      No archived timetracker projects"
			die
		fi
	}

	if [[ "${project}" = "usage" ]]; then
		localUsage
		exit
	# If no project was set, show all projects stats
	elif [ ${ALL} -eq 1 ]; then
		cd "${TODO_DIR}/tt/${PRE}/archive" || exit 1
		for project in *.tt; do
			project="${project/%???/}"
			_archivedstats "${project}"
		done
	else
		# Find all projects given on command line
		# shellcheck disable=SC2068
		for project in $@; do
			# Remove .tt
			project="${project/#+/}"
			_archivedstats "${project}"
		done
	fi
}

ttstatsall () {
	localUsage () {
    echo "    $(basename "$0") ${action}"
    echo "      Show stats on all projects"
	}
	if [[ "${project}" = "usage" ]]; then
		localUsage
		exit
	# If we have no projects, error out
	elif [[ -z "${CURRENT}" ]] && [[ -z "${ARCHIVED}" ]]; then
		localUsage
		echo "      No timetracker projects exist"
		die
	fi
	# If we have current projects
	if [[ -n "${CURRENT}" ]]; then
		ttstats $(ttsimplelist)
	fi
	# If we have archived projects
	if [[ -n "${ARCHIVED}" ]]; then
			ttarchivedstats $(ttsimplearchivedlist)
	fi
}
# Main
case "${action}" in
	stats)
		ttstats "${@}"
	;;
	archivedstats)
		ttarchivedstats "${@}"
	;;
	statsall)
		ttstatsall
	;;
	on)
		tton "$@"
	;;
	off)
		ttoff "$@"
	;;
	list)
		ttlist
	;;
	archive)
		ttarchive "$@"
	;;
	unarchive)
		ttunarchive "$@"
	;;
	simplelist)
		ttsimplelist
	;;
	simplearchivedlist)
		ttsimplearchivedlist
	;;
	simplelistall)
		ttsimplelistall
	;;
	*)
		usage
	;;
esac