#!/bin/bash
# 2009 Paul Mansfield
# License:  GPL, http://www.gnu.org/copyleft/gpl.html
case $1 in
"usage")
  echo "$(basename $0) [BASENAME]"
  echo "  Show Projects and tasks in task order"
  ;;
*)
echo -e "=====Projects=====\n"
PROJECTS=`grep -o '[^ ]*+[^ ]\+' "$TODOTXT_TODO_FILE" | grep '^+' | sort -u | sed 's/^+//g'` 
	for i in $PROJECTS ; do 
		echo -e "--- $i ---"
		grep "+$i" "$TODOTXT_TODO_FILE" | sort -t [ -k 2
		echo -e
	done
	echo -e "---Not a project---"
	grep -v "+\w" "$TODOTXT_TODO_FILE"
  ;;
esac
