#!/usr/bin/env bash
# shellcheck shell=bash
#===============================================================================
#
#          FILE: enotesadd
#
#         USAGE: todo.sh enotesadd [ITEM] [ENOTESFILE]
#
#        AUTHOR: Paul Mansfield (paul.mansfield@mansteck.co.uk), 
#     COPYRIGHT: 2009-2021 Paul Mansfield
#       LICENSE: GPL, http://www.gnu.org/copyleft/gpl.html
#===============================================================================

usage () {
	echo "    $(basename "$0") [ITEM...] [ENOTESFILE]"
	echo "      add ENOTESFILE to ITEMS"
}

die () {
	if [[ -n $* ]]; then
		echo -e "$*"
  fi
	usage
	exit 1
}

# Usage for todo.sh help or remove action
if [[ "${1}" = "usage" ]] || [[ "${2}" = "usage" ]]; then
	usage
	exit
elif [[ "${1}" = "$(basename "$0")" ]]; then
  shift
fi

# Check enotes and item number exist
if [[ "$#" -lt 2 ]]; then
  if [[ "$1" =~ ^[0-9]+$ ]]; then
    die "      No enotesfile given"
  elif ! [[ "$1" =~ ^[0-9]+$ ]]; then
    die "      No item given"
  fi
fi

# Check notes and archive exist
mkdir -p "${TODO_DIR}/notes/archive" || exit 1
cd "${TODO_DIR}/notes" || exit 1

# Set enotes file from last argument and remove last argument
# this leaves items which we test later
ENOTES_FILE=${!#};
ENOTES_FILE="${ENOTES_FILE/#enote:/}"
set -- "${@:1:$(($#-1))}"
PRE="$(basename "${TODO_FILE}" | sed 's/.enc$//g')"
ENOTES=$(find . -maxdepth 1 -name "${PRE}*enc" -printf '%P\n')

# If our enotes file is just numbers we didn't get given one
if [[ "${ENOTES_FILE}" =~ ^[0-9]+$ ]]; then
  die "      No enotesfile given"
fi

# Can we edit after addition?
# Only set if file new to todo.txt and note doesn't exist
# Also check we have notesedit addon installed
if [[ "${NOTE_ADD_EDIT}" = "OFF" ]]; then
  if [[ $(grep -c "${ENOTES_FILE}" "${TODO_FILE}") -eq 0 ]] && \
    ! [[ -f "${TODOTXT_DIR}/notes/${PRE}-${ENOTES}.txt" ]] && \
    [[ $(${TODO_FULL_SH} listaddons | grep -c ^enotesedit$) -eq 1 ]]; then
    EDIT_FILE=1
  fi
fi

# Are items in the file?
# shellcheck disable=SC2068
for item in $@; do
  if [[ ${item} -gt $(wc -l "${TODO_FILE}" | cut -f 1 -d " ") ]]; then
    die "      No item ${item}"
  fi
done

# Are items in the file?
# shellcheck disable=SC2068
for item in $@; do
  # Test we have an item number
  if ! [[ "${item}" =~ ^[0-9]+$ ]]; then
    die "	ITEM is not a number"
  fi
  "${TODO_FULL_SH}" append "${item}" "enote:${ENOTES_FILE}"
  echo "$(getPrefix "${TODO_FILE}"): enote:${ENOTES_FILE} added to item ${item}"
done

# If our tests allow open file for editing
if [[ "${EDIT_FILE}" = 1 ]]; then
  "${TODO_FULL_SH}" enotesedit "enote:${ENOTES_FILE}"
fi