#!/usr/bin/env bash
# shellcheck shell=bash
#===============================================================================
#
#          FILE: enotesunarchive
#
#         USAGE: todo.sh enotesunarchive [ENOTESFILE]
#
#        AUTHOR: Paul Mansfield (paul.mansfield@mansteck.co.uk), 
#     COPYRIGHT: 2009-2021 Paul Mansfield
#       LICENSE: GPL, http://www.gnu.org/copyleft/gpl.html
#===============================================================================

usage() {
  echo "    $(basename "$0") [ENOTESFILE]"
  echo "      unarchive enotes files, this brings back the last"
  echo "      version of the enotefile"
}

die () {
  if [[ -n $* ]]; then
    echo -e "$*"
  fi
  usage
	exit 1
}

# Usage for todo.sh help or remove action
if [[ "${1}" = "usage" ]] || [[ "${2}" = "usage" ]]; then
  usage
  exit
elif [[ "${1}" = "$(basename "$0")" ]]; then
  shift
fi

# Check notes and archive exist
mkdir -p "${TODO_DIR}/notes/archive" || exit 1
cd "${TODO_DIR}/notes/archive" || exit 1

FILE=${1##enote:}; shift
PRE="$(basename "${TODO_FILE}")"; PRE=${PRE/%\.txt/}
DATE_FILE=$(find -- * -name "${PRE}-${FILE}.*.enc" -type f -printf "%T@ %p\n"  2> /dev/null | sort -n | cut -f 2 -d " "  | tail -n 1)
ARC_FILE="${TODO_DIR}/notes/archive/${DATE_FILE}"
ENOTES_FILE="${TODO_DIR}/notes/${PRE}-${FILE}.enc"
TODO_TMP_FILE="${TODO_TMP_FILE:-${TODO_DIR}/todo.tmp}"

if [[ -z "${DATE_FILE}" ]]; then
  die "      No archived enotes file named ${FILE}. Use listarchivedenotes to find them"
fi

# Does the notes file exist? i.e  mentioned in todo/tickled file?
cat "${TODO_FILE}" > "${TODO_TMP_FILE}"
if [[ -n ${TICKLER_DIR} ]] && [[ -d ${TICKLER_DIR} ]]; then
  find "${TICKLER_DIR}" -mindepth 2 -type f -size 1 -exec cat {} \; >> "${TODO_TMP_FILE}"
fi
if [[ "$(grep -c "\benote:${FILE}\b" "${TODO_TMP_FILE}")" -eq 0 ]] ;then
  die "      Encrypted note file ${FILE} not mentioned in todo. Use listenotes to find them"
fi
[[ -f "${TODO_TMP_FILE}" ]] && rm -rf "${TODO_TMP_FILE}"

cp "${ARC_FILE}" "${ENOTES_FILE}" 
if [[ "$?" -eq 1 ]]; then
  die "      Unable to move ${PRE}-${FILE}.enc to ${NO_DATE_FILE}.enc"
else
  echo "$(getPrefix): Encrypted notes file ${PRE}-${FILE}.enc restored from newest archive"
fi