#!/usr/bin/env bash
# shellcheck shell=bash
#===============================================================================
#
#          FILE: enotesarchive
#
#         USAGE: todo.sh enotesarchive
#
#        AUTHOR: Paul Mansfield (paul.mansfield@mansteck.co.uk), 
#     COPYRIGHT: 2009-2021 Paul Mansfield
#       LICENSE: GPL, http://www.gnu.org/copyleft/gpl.html
#===============================================================================

usage () {
	echo "    $(basename "$0")"
	echo "      archive encrypted notes files nolonger in todo file."
}

die () {
	if [[ -n $* ]]; then
		echo -e "$*"
	fi
	usage
	exit 1
}

# Usage for todo.sh help or remove action
if [[ "${1}" = "usage" ]] || [[ "${2}" = "usage" ]]; then
	usage
	exit
elif [[ "${1}" = "$(basename "$0")" ]]; then
  shift
fi

# Check notes and archive exist
mkdir -p "${TODO_DIR}/notes/archive" || exit 1
cd "${TODO_DIR}/notes" || exit 1
TODO_TMP_FILE="${TODO_TMP_FILE:-${TODO_DIR}/todo.tmp}"

# construct file name
PRE="$(basename "${TODO_FILE}" | sed 's/.txt$//g')"
ENOTES=$(find . -maxdepth 1 -name "${PRE}*enc" -printf '%P\n')

# Create file from todo and 'tickled' files
cat "${TODO_FILE}" > "${TODO_TMP_FILE}"
if [[ -n "${TICKLER_DIR}" ]]; then
	find "${TICKLER_DIR}" -mindepth 2 -type f -size 1 -exec cat {} \; >> "${TODO_TMP_FILE}"
fi

RETURN=0
# for each file, remove $PRE and see if its in todo or 'tickled' files
for i in ${ENOTES} ; do
	ENOTE_FILE="$(echo "$i"  | sed -e "s/${PRE}-//g" -e "s/[.]enc//g")"
  # Number of times enote appears in todo.txt
  NUM_ENOTE=$(grep -c "[^ ]*enote:${ENOTE_FILE}[^ ]\+" "${TODO_TMP_FILE}")
	# if enote isn't in our todo file, archive in notes/archive/
	if [[ "${NUM_ENOTE}" -eq 0 ]] ;then
    cat "${TODO_DIR}/notes/${PRE}-${ENOTE_FILE}.enc" >> \
      "${TODO_DIR}/notes/archive/${PRE}-${ENOTE_FILE}.$(date +%s).enc" || \
        die "      unable to create archive file" && \
    rm "${TODO_DIR}/notes/${PRE}-${ENOTE_FILE}.enc"
    echo "$(getPrefix): Archived enote:${ENOTE_FILE}"
    ((RETURN+=1)) 
    # If we are using commit action then add to git
    if [ -e "${TODOTXT_ACTIONS_DIR}/commit" ]; then
        git add "${TODO_DIR}/notes/archive/${PRE}-${ENOTE_FILE}.$(date +%s).enc"
    fi
	fi
done

[[ -f "${TODO_TMP_FILE}" ]] && rm -rf "${TODO_TMP_FILE}"

# if we have not archived anything, then report
if [[ -z "${RETURN}" ]]; then
  echo "$(getPrefix): Nothing to archive"
  exit 1
fi