#!/usr/bin/env bash
# shellcheck shell=bash
#===============================================================================
#
#          FILE: enotescat
#
#         USAGE: todo.sh enotescat [ENOTESFILE]
#
#        AUTHOR: Paul Mansfield (paul.mansfield@mansteck.co.uk), 
#     COPYRIGHT: 2009-2021 Paul Mansfield
#       LICENSE: GPL, http://www.gnu.org/copyleft/gpl.html
#===============================================================================

usage () {
  echo "    $(basename "$0") [ENOTESFILE]"
  echo "      Cat encrypted notes file, use listenotes to get list of notes"
}

# Remove action
shift
# Tests and show usage
if [[ "${1}" = "usage" ]] || [[ "${1}" = "-h" ]]; then
	usage
	exit
elif [[ $# -lt 1 ]]; then
  echo "      not enough options"
  usage
  exit 1
fi
# shellcheck disable=SC2001
ENOTE_FILE="$(echo "${1}" | sed 's/^enote://g')"
PRE="$(basename "${TODO_FILE}" | sed 's/.txt$//g')"

if  [[ $(grep -c "${ENOTE_FILE}" "${TODO_FILE}") -lt 1 ]]; then
  echo "      Encrypted notes file $1 not in todo.txt file,"
  echo "      use listenotes to find encrypted notes files"
  usage
  exit 1
fi

if [ -e "${TODO_DIR}/notes/${PRE}-${ENOTE_FILE}.enc" ]; then
    gpg -dq "${TODO_DIR}/notes/${PRE}-${ENOTE_FILE}.enc"
fi