#!/usr/bin/env bash
# shellcheck shell=bash
#===============================================================================
#
#          FILE: enotesedit
#
#         USAGE: todo.sh enotesedit [ENOTESFILE]
#
#        AUTHOR: Paul Mansfield (paul.manfield@mansteck.co.uk), 
#     COPYRIGHT: 2009-2021 Paul Mansfield
#       LICENSE: GPL, http://www.gnu.org/copyleft/gpl.html
#===============================================================================

usage () {
	echo "    $(basename "$0") [ENOTESFILE]"
	echo "      Edit encrypted ENOTESFILE in \$EDITOR."
	echo "      Use listenotes to show all encrypted notes files."
}

die () {
	if [[ -n $* ]]; then
		echo -e "$*"
	fi
	usage
	exit 1
}

# Find editor to use
# Use debian and derivatives editor (alternatives auto set by OS), then
# if EDITOR already set use, else if EDITOR not set default to vi
find_editor () {
  if [[ -n ${EDITOR} ]]; then
    true
	elif [[ -L /usr/bin/editor ]]; then
		EDITOR="/usr/bin/editor"
	elif [[ "${EDITOR}x" = "x" ]]; then
		EDITOR="vi"
	fi
  echo "${EDITOR}"
}

# Usage for todo.sh help or remove action
if [[ "${1}" = "usage" ]] || [[ "${2}" = "usage" ]]; then
	usage
	exit
elif [[ "${1}" = "$(basename "$0")" ]]; then
  shift
fi

ENOTE_FILE="${1/#enote:/}"; shift
PRE="$(basename "${TODO_FILE}")"; PRE=${PRE/%\.txt/}
TODO_TMP_FILE="${TODO_TMP_FILE:-${TODO_DIR}/todo.tmp}"
EDITOR=$(find_editor)

if [[ -z "${ENOTE_FILE}" ]]; then
  die "      No encryted notes file"
elif  [[ $(grep -c "${ENOTE_FILE}" "${TODO_FILE}") -eq 0 ]]; then
	die "      Encrypted notes file $1 not in todo.txt file,\n      use listenotes to find encrypted notes files"
elif [[ -z "${GPG_USER}" ]]; then
  die "      Please set a variable GPG_USER in your todo.cfg"
fi


# Create file from todo and 'tickled' files since enotes could be in tickled file
cat "${TODO_FILE}" > "${TODO_TMP_FILE}"
if [ -n "${TICKLER_DIR}" ]; then
	find "${TICKLER_DIR}" -mindepth 2 -type f -size 1 -exec cat {} \; >> "${TODO_TMP_FILE}"
fi

# If file exists edit it, else check listenotes for pointer then edit 
if [ -e "${TODO_DIR}/notes/${PRE}-${ENOTE_FILE}.enc" ]; then
	# Decrypt, move old aside, edit, encrypt and tidy up
	gpg -dq -o "${TODO_TMP_FILE}.encrypt" "${TODO_DIR}/notes/${PRE}-${ENOTE_FILE}.enc" > /dev/null 2>&1 \
    || die "      Unable to decrypt ${PRE}-${ENOTE_FILE}.enc"
	mv "${TODO_DIR}/notes/${PRE}-${ENOTE_FILE}.enc" "${TODO_DIR}/notes/${PRE}-${ENOTE_FILE}.enc.bak"
	"${EDITOR}" "${TODO_TMP_FILE}.encrypt"
	gpg -eq --batch -r "${GPG_USER}" -o "${TODO_DIR}/notes/${PRE}-${ENOTE_FILE}.enc" "${TODO_TMP_FILE}.encrypt" \
		|| die "			Unable to encrypt ${TODO_DIR}/notes/${PRE}-${ENOTE_FILE}.enc"
  # shellcheck disable=SC2181
	if [ "$?" -eq 0 ] ; then
		rm -rf "${TODO_DIR}/notes/${PRE}-${ENOTE_FILE}.enc.bak"
	else
		mv "${TODO_DIR}/notes/${PRE}-${ENOTE_FILE}.enc.bak" "${TODO_DIR}/notes/${PRE}-${ENOTE_FILE}.enc"
	fi
	[[ -f "${TODO_TMP_FILE}.encrypt" ]] && rm -rf "${TODO_TMP_FILE}.encrypt"
else
	# If enote link in todo.txt exists then edit
	# shellcheck disable=SC2046,SC2086
  NUM_ENOTE=$(grep -c "[^ ]*enote:${ENOTE_FILE}[^ ]\+" "${TODO_TMP_FILE}")
	if [ "${NUM_ENOTE}" -ge 1 ] ; then
		# edit file, encrypt and tidy up
		"${EDITOR}" "${TODO_TMP_FILE}.encrypt"
	 	gpg -eq --batch -r "${GPG_USER}" -o "${TODO_DIR}/notes/${PRE}-${ENOTE_FILE}.enc" "${TODO_TMP_FILE}.encrypt" \
    || die "			Unable to decrypt ${TODO_DIR}/notes/${PRE}-${ENOTE_FILE}.enc"
		[[ -f "${TODO_TMP_FILE}.encrypt" ]] && rm -rf "${TODO_TMP_FILE}.encrypt"
	fi
fi