#!/usr/bin/env bash
# shellcheck shell=bash
#===============================================================================
#
#          FILE: enotesrename
#
#         USAGE: todo.sh enotesrename [ORIGINAL_ENOTESFILE] [NEW_ENOTESFILE]
#
#        AUTHOR: Paul Mansfield (paul.mansfield@mansteck.co.uk), 
#     COPYRIGHT: 2009-2021 Paul Mansfield
#       LICENSE: GPL, http://www.gnu.org/copyleft/gpl.html
#===============================================================================

# functions
usage () {
	echo "    $(basename "$0") [ORIGINAL_ENOTESFILE] [NEW_ENOTESFILE]"
	echo "      rename ORIGINAL_ENOTESFILE to NEW_ENOTESFILE"
  echo "      renames in todo.txt and enotefile"
	echo "      the enote: is not required, but added"
}

die () {
  if [[ -n $* ]]; then
    echo -e "$*"
  fi
  usage
	exit 1
}

# Usage for todo.sh help or remove action
if [[ "${1}" = "usage" ]] || [[ "${2}" = "usage" ]]; then
  usage
  exit
elif [[ "${1}" = "$(basename "$0")" ]]; then
  shift
fi
OLD_FILE=$(_note_fix "$1")
NEW_FILE=$(_note_fix "$2")
PRE=$(basename "${TODO_FILE}" | sed 's/.txt$//g')
NOTES_DIR="${TODO_DIR}/notes"

if [[ "$#" -ne 2 ]]; then
  die "    check number of options"
fi

OLD_FILE=${1##enote:}
NEW_FILE=${2##enote:}

RETURN=0
if [[ "$(grep -c "${OLD_FILE}" "${TODO_FILE}")" -ge 1 ]]; then
	sed -i "s/note:${OLD_FILE}\b/enote:${NEW_FILE}/g" "${TODO_FILE}"
  echo "$(getPrefix): Changed enote:${OLD_FILE} to enote:${NEW_FILE} in todo.txt"
  ((UPDATE+=1))
  ((RETURN+=1))
fi
if [[ "$(grep -c "${OLD_FILE}" "${DONE_FILE}")" -ge 1 ]]; then
	sed -i "s/note:${OLD_FILE}\b/enote:${NEW_FILE}/g" "${DONE_FILE}"
  echo "$(getPrefix): Changed enote:${OLD_FILE} to enote:${NEW_FILE} in done.txt"
  ((UPDATE+=1))
  ((RETURN+=1))
fi
if [[ -z "${UPDATE}" ]]; then
	die "    ${OLD_FILE} is not a current enote, use listenotes to find enotes."
fi

# Test the OLD_FILE exists and RENAME
# Remove the enote: to be used as filename
if [[ -f "${NOTES_DIR}/${PRE}-${OLD_FILE}.enc" ]]; then
	mv "${NOTES_DIR}/${PRE}-${OLD_FILE}.enc" "${NOTES_DIR}/${PRE}-${NEW_FILE}.enc"
fi

# Test for OLD_FILE in 'tickled' files and rename
if [[ -n ${TICKLER_DIR} ]]; then
	TICKLED="$(find "${TICKLER_DIR}" -mindepth 2 -type f -size 1 -exec grep -l "${OLD_FILE}" {} \;)"
	for FILE in ${TICKLED}; do
		# shellcheck disable=SC1117
		sed -i "s/enote:${OLD_FILE}\b/enote:${NEW_FILE}" "${FILE}"
    echo "$(getPrefix "${TODO_FILE}"): Changed enote:${OLD_FILE} to enote:${NEW_FILE} in tickled file"
	done
  if [[ -f "${NOTES_DIR}/${OLD_FILE}.enc" ]]; then
    mv "${NOTES_DIR}/${OLD_FILE}.enc" "${NOTES_DIR}/${NEW_FILE}.enc"
  fi
fi

if [[ -n "${RETURN}" ]]; then
  exit 0
else
  exit 1
fi