#!/usr/bin/env bash
# 2009 Paul Mansfield <paul.mansfield@mansteck.co.uk>
# License:  GPL, http://www.gnu.org/copyleft/gpl.html

case $1 in
"usage")
    echo "  $(basename $0) [NOTESFILE]"
    echo "    Cat encyrpted notes file, use lsenotes to get list of notes"
    echo ""
;;

*)
    if [ $# -lt 2 ]; then
        $0 usage
        exit 1
    fi
    NOTE_FILE=$(echo $2 | sed 's/^enote://g')
    PRE=$(basename $TODO_FILE | sed 's/.enc$//g')
    if [ -e $TODO_DIR/notes/${PRE}-${NOTE_FILE}.enc ]; then
        gpg -d $TODO_DIR/notes/${PRE}-${NOTE_FILE}.enc
        echo ""
    else
        echo "No such encrypted notes file, use lsenotes to find encrypted notes files"
    fi
;;
esac
