#!/usr/bin/env bash
# shellcheck shell=bash
#===============================================================================
#
#          FILE: listarchivedenotes 
#
#         USAGE: todo.sh listarchivedenotes [TERM]
#
#        AUTHOR: Paul Mansfield (paul.mansfield@mansteck.co.uk), 
#     COPYRIGHT: 2009-2021 Paul Mansfield
#       LICENSE: GPL, http://www.gnu.org/copyleft/gpl.html
#===============================================================================

usage() {
	echo "    $(basename "$0") [TERM]" 
	echo "      List archived encrypted notes"
}

die () {
  if [[ -n $* ]]; then
    echo -e "$*"
  fi
  usage
	exit 1
}

# Usage for todo.sh help or remove action
if [[ "${1}" = "usage" ]] || [[ "${2}" = "usage" ]]; then
  usage
  exit
elif [[ "${1}" = "$(basename "$0")" ]]; then
  shift
fi

PRE="$(basename "${TODO_FILE}")"; PRE=${PRE/%\.txt/}
TODO_TMP_FILE="${TODO_TMP_FILE:-${TODO_DIR}/todo.tmp}"

# Check notes and archive exist
mkdir -p "${TODO_DIR}/notes/archive/" || exit 1
cd "${TODO_DIR}/notes/archive/" || exit 1

# Find a list of files
find . -name "${PRE}-*enc" -printf '%P\n' | grep "^${PRE}-" | \
  sed  -e "s/^${PRE}-//g" -e "s/^/enote:/g" -e "s/\.enc$//g" -e "s/\.[0-9]\{1,10\}$//g" > \
  "${TODO_TMP_FILE}"
if [[ $(grep -c "$*" "${TODO_TMP_FILE}") -gt 0 ]]; then
  grep "$*" "${TODO_TMP_FILE}"
  [[ -f "${TODO_TMP_FILE}" ]] && rm -rf "${TODO_TMP_FILE}"
else
  [[ -f "${TODO_TMP_FILE}" ]] && rm -rf "${TODO_TMP_FILE}"
  die "      No notes with the term \"$*\""
fi