#!/usr/bin/env bash
# ======= tickle action plugin for Gina Trapani's todo.sh =======
# Adapted from (Tanja's tickler patch for todo.sh)[http://tanniespace.com/tickler-files-and-todosh/]
# Version: 0.1
# Adapted as plugin by:  Braden Grams
# Tidy up and adapted for newer todo.sh versions
# License: GPL, http://www.gnu.org/copyleft/gpl.html

usage()
{
    sed -e 's/^    //' <<EndUsage 
        tickle NUMBER [dmNUMBER]
          Move a line from todo.txt to day or month file in $TODODIR/Tickler/.
          If [dm]<number> is omitted you will be prompted to enter a day or
          month number.
EndUsage
    exit 1
}

die()
{
    echo "$*"
    exit 1
}

cleanup()
{
    [ -f "$TMP_FILE" ] && rm "$TMP_FILE"
    exit 0
}

#=== HEAVY LIFTING ===
shopt -s extglob


action=$1
case $action in
    "usage")
    usage
    ;;
    "tickle" )
   	item=$2;
   	[ -z "$item" ] && usage
   	[[ "$item" = +([0-9]) ]] || usage

    datetype=$3; 
    
    # If we don't have date details ask for them.
    if [ -z "$datetype" ]; then
    echo "Tickle to day or month folder?  (d/m)"
    read ANSWER
        if [ "$ANSWER" = "d" ]; then
            FOLDER="days"
            echo "Tickle to which day folder?"
            read NUMBER
        elif [ "$ANSWER" = "m" ]; then
            FOLDER="months"
            echo "Tickle to which month folder?"
            read NUMBER
        fi
    else
        # If we are already given date details, check before using
        if [ $(echo $datetype | grep -c "^[dDmM][0-9]\{1,2\}$") -ne 1 ]; then
            usage
        fi

        # Are we going to use a day or month tickle file?
        if expr "$datetype" : ' *[dD].*' > /dev/null; then
            FOLDER="days"
            NUMBER="$(echo $datetype | sed 's/d//')"
        elif expr "$datetype" : ' *[mM].*' > /dev/null; then
            FOLDER="months"
            NUMBER="`echo $datetype | sed 's/m//'`"
        fi
    fi
    
    # Add leading zeros
    LENGTH=$(expr "$NUMBER" : ".*")
    if [ "$LENGTH" = "1" ]; then
               NUMBER="0$NUMBER"
    fi

    # Main work, find the item to be tickled
    if [ $(sed -ne "$item p" "$TODO_FILE" | grep -c "^.") -eq 1 ]; then
    DELETEME=$(sed "$item!d" "$TODO_FILE")
    else
        echo "Item number $item does not exist in todo file."
        usage
    fi

    # Check we have the required directories, if not create them
    if [ ! -e $TICKLER_DIR/$TYPE/$FOLDER/$NUMBER/ ]; then
        mkdir -p $TICKLER_DIR/$TYPE/$FOLDER/$NUMBER/
    fi

    # Write the tickle file, then remove from the todo.txt file
    echo $DELETEME >> $TICKLER_DIR/$TYPE/$FOLDER/$NUMBER/$NUMBER.txt
    sed -i.bak -e $2"s/^.*//" -e '/./!d' "$TODO_FILE"
    echo "Moved todo $2 to $TICKLER_DIR/$TYPE/$FOLDER/$NUMBER/$NUMBER.txt"
    cleanup
    ;;
esac
