#!/bin/bash
# 2009 Paul Mansfield
# License:  GPL, http://www.gnu.org/copyleft/gpl.html

# Stop Verbose lines, thanks to Mark Harrison
TODOTXT_VERBOSE=0

case $1 in
"usage")
  echo "$(basename $0) [BASENAME]"
  echo "  Show Projects and todo items in priority order"
  ;;
*)
# Show projects in alphabetical order and todo items in priority  order
echo -e "===== Projects =====\n"
# Find all projects and sort
PROJECTS=`grep -o '[^ ]*+[^ ]\+' "$TODO_FILE" | grep '^+' | sort -u | sed 's/^+//g'` 
# For each project show header and the list of todo items
for i in $PROJECTS ; do 
	echo -e "--- $i ---"
	# Use core _list function, does numbering and colouring for us
	_list "$TODO_FILE" "+$i" | sed 's/+[a-zA-Z0-9\{._\-\}]*//g'
 echo -e "\n"
done
# Show todo items not associated to a project
echo -e "--- Not in projects ---"
_list "$TODO_FILE" | grep -v "+\w"
  ;;
esac
