#!/usr/bin/env bash
# 2009 Paul Mansfield <paul.mansfield@mansteck.co.uk>
# License:    GPL, http://www.gnu.org/copyleft/gpl.html

# Functions
usage() {
	echo "  $(basename $0)"
	echo "    List notes"
	echo ""
}

# Usage for todo.sh help
if [ "$1" = "usage" ]; then
	usage
	exit
fi

# Variables
action="$1"; shift

case $1 in
	"usage")
		usage
		exit
	;;

	"-h")
		usage
	;;

	*)
		# Create file from todo and 'tickled' files
		cat $TODO_FILE>> $TMP_FILE
		if [ -n $TICKLER_DIR ]; then
			find $TICKLER_DIR -mindepth 2 -size 1b -exec cat {} >>$TMP_FILE \;
		fi
		grep -o '\bnote\:[a-zA-Z_-]*' "$TMP_FILE" | sort -u
	;;
esac
