#!/usr/bin/env bash
# shellcheck shell=bash
#===============================================================================
#
#          FILE: listarchivednotes 
#
#         USAGE: todo.sh listarchivednotes [TERM]
#
#        AUTHOR: Paul Mansfield (paul.mansfield@mansteck.co.uk), 
#     COPYRIGHT: 2009-2021 Paul Mansfield
#       LICENSE: GPL, http://www.gnu.org/copyleft/gpl.html
#===============================================================================

usage() {
	echo "    $(basename "$0") [TERM]"
	echo "      List archived notes"
}


# Remove action
shift
PRE=$(basename "${TODO_FILE}" | sed 's/.txt$//g')
TODO_TMP_FILE="${TODO_TMP_FILE:-${TODO_DIR}/todo.tmp}"

# Usage for todo.sh help
if [[ "${1}" = "usage" ]] || [[ "${1}" = "-h" ]]; then
	usage
	exit
fi

mkdir -p "${TODO_DIR}/notes/archive/" || exit 1
cd "${TODO_DIR}/notes/archive/" || exit 1

# Find a list of files
find . -type f -regex ".*\.txt" -printf '%P\n'  | grep "^${PRE}-" \
  | sed  -e "s/${PRE}-//" -e 's/.txt$//' > "${TODO_TMP_FILE}"
if [[ $(grep -c "$*" "${TODO_TMP_FILE}") -gt 0 ]]; then
  if [[ "$#" -eq 0 ]]; then
    sed 's/^/note:/' "${TODO_TMP_FILE}"
  else
    sed 's/^/note:/' "${TODO_TMP_FILE}" | grep "$*"
  fi
else
  echo "No notes with the term \"$*\""
fi
[[ -f "${TODO_TMP_FILE}" ]] && rm -rf "${TODO_TMP_FILE}"