#!/usr/bin/env bash
# shellcheck shell=bash
#===============================================================================
#
#          FILE: listarchivednotes 
#
#         USAGE: todo.sh listarchivednotes [TERM]
#
#        AUTHOR: Paul Mansfield (paul.mansfield@mansteck.co.uk), 
#     COPYRIGHT: 2009-2021 Paul Mansfield
#       LICENSE: GPL, http://www.gnu.org/copyleft/gpl.html
#===============================================================================

usage() {
	echo "    $(basename "$0") [TERM]"
	echo "      List archived notes"
}

die () {
  if [[ -n $* ]]; then
    echo -e "$*"
  fi
  usage
	exit 1
}

# Usage for todo.sh help or remove action
if [[ "${1}" = "usage" ]] || [[ "${2}" = "usage" ]]; then
	usage
	exit
elif [[ "${1}" = "$(basename "$0")" ]]; then
  shift
fi

mkdir -p "${TODO_DIR}/notes/archive/" || exit 1
cd "${TODO_DIR}/notes/archive/" || exit 1

# Find a list of files
find . -type f -regex ".*\.txt" -printf '%P\n'  | grep "^${PRE}-" \
  | sed  -e "s/${PRE}-//" -e 's/.txt$//' > "${TODO_TMP_FILE}"
if [[ $(grep -c "$*" "${TODO_TMP_FILE}") -gt 0 ]]; then
  if [[ "$#" -eq 0 ]]; then
    sed 's/^/note:/' "${TODO_TMP_FILE}"
  else
    sed 's/^/note:/' "${TODO_TMP_FILE}" | grep "$*"
  fi
else
  echo "No notes with the term \"$*\""
fi
[[ -f "${TODO_TMP_FILE}" ]] && rm -rf "${TODO_TMP_FILE}"