#!/usr/bin/env bash
# shellcheck shell=bash
#===============================================================================
#
#          FILE: notesgrep
#
#         USAGE: todo.sh notesgrep TERM
#
#        AUTHOR: Paul Mansfield (paul.mansfield@mansteck.co.uk), 
#     COPYRIGHT: 2009-2021 Paul Mansfield
#       LICENSE: GPL, http://www.gnu.org/copyleft/gpl.html
#===============================================================================

usage () {
	echo "    $(basename "$0") [-a] [TERM...]"
	echo "      List notes that contain a TERM within them"
	echo "      -a show archived notes"
}

die () {
  if [[ -n $* ]]; then
    echo -e "$*"
  fi
  usage
	exit 1
}

# Usage for todo.sh help or remove action
if [[ "${1}" = "usage" ]] || [[ "${2}" = "usage" ]]; then
  usage
  exit
elif [[ "${1}" = "$(basename "$0")" ]]; then
  shift
fi

if [[ -z "$1" ]]; then
  die "    No TERM"
fi
PRE="$(basename "${TODO_FILE}" | sed 's/.txt$//g')"
# Our active notes files
  # shellcheck disable=SC2086
NOTES="$(find ${PRE}-*.txt)"
# Our archived notes files
  # shellcheck disable=SC2086
ARCHIVED="$(find archive/${PRE}-*.txt)"
if [[ "$1" = "-a" ]]; then
	ARCHIVE=1; shift
fi

## Main
TOTAL_NOTES=0
for item in ${NOTES}; do
  # shellcheck disable=SC2086
  if [[ "$(grep -oc "$*" ${item})" -gt 0 ]]; then
  ((TOTAL_NOTES=+1))
  fi
done
TOTAL_ARCHIVED=0
for item in ${ARCHIVED}; do
  # shellcheck disable=SC2086
  if [[ "${ARCHIVE}" -eq 1 ]] && [[ "$(grep -oc "$*" ${item})" -gt 0 ]]; then
    ((TOTAL_ARCHIVED=+1))
  fi
done

if [[ "${TOTAL_NOTES}" -gt 0 ]]; then
  echo "Notes Files containing \"$*\""
  echo "-----------"
  # shellcheck disable=SC2086
  grep -l "$*" ${NOTES} | sed "s/^.*${PRE}-/note:/g ; s/[.]txt$//g"
else
  echo "No current Notes containing \"$*\""
  ((RETURN+=1))
fi
if [[ ${ARCHIVE} -eq 1 ]]; then
  # shellcheck disable=SC2086
  # if [ "$(grep -o "$*" ${ARCHIVED} | wc -l)" -gt 0 ]; then
  if [ ${TOTAL_ARCHIVED} -gt 0 ]; then
    echo ""
    echo "Archived Notes Files containing \"$*\""
    echo "--------------------"
    # shellcheck disable=SC2086
    grep -l "$*" ${ARCHIVED} | sed "s/^.*${PRE}-/note:/g ; s/[.]txt$//g"
  else
    echo "No current archived Notes containing \"$*\""
    ((RETURN+=1))
  fi
fi
if [[ ${RETURN} -gt 0 ]]; then
  exit 1
fi