#!/usr/bin/env bash
# shellcheck shell=bash
#===============================================================================
#
#          FILE: notesarchive
#
#         USAGE: todo.sh notesarchive
#
#        AUTHOR: Paul Mansfield (paul.mansfield@mansteck.co.uk), 
#     COPYRIGHT: 2009-2021 Paul Mansfield
#       LICENSE: GPL, http://www.gnu.org/copyleft/gpl.html
#===============================================================================

usage() {
  echo "    $(basename "$0")"
  echo "      archive notes files nolonger in todo file."
}

die () {
	if [[ -n $* ]]; then
		echo -e "$*"
	fi
	usage
	exit 1
}

# Usage for todo.sh help or remove action
if [[ "${1}" = "usage" ]] || [[ "${2}" = "usage" ]]; then
	usage
	exit
elif [[ "${1}" = "$(basename "$0")" ]]; then
  shift
fi

# Check notes and archive exist
mkdir -p "${TODO_DIR}/notes/archive" || exit 1
cd "${TODO_DIR}/notes" || exit 1

# construct file name
PRE="$(basename "${TODO_FILE}" | sed 's/.txt$//g')"
TODO_TMP_FILE="${TODO_TMP_FILE:-${TODO_DIR}/todo.tmp}"
NOTES=$(find . -maxdepth 1 -name "${PRE}-*txt" -printf '%P\n')

# Create file from todo and 'tickled' files
cat "${TODO_FILE}" > "${TODO_TMP_FILE}"
if [[ -n "${TICKLER_DIR}" ]] && [[ -d "${TICKLER_DIR}" ]]; then
	find "${TICKLER_DIR}" -mindepth 2 -type f -size 1 -exec cat {} \; >> "${TODO_TMP_FILE}"
fi

# for each file, remove $PRE and see if its in todo or 'tickled' files
for i in ${NOTES} ; do
	i="${i/#${PRE}-/}"; NOTE_FILE="${i/%\.txt/}"
	# Number of times note appears in todo.txt
  NUM_NOTE=$(grep -c "\bnote:${NOTE_FILE}\b" "${TODO_TMP_FILE}")
	if [[ "${NUM_NOTE}" -eq 0 ]] ;then
		cat "${TODO_DIR}/notes/${PRE}-${NOTE_FILE}.txt" >> \
			"${TODO_DIR}/notes/archive/${PRE}-${NOTE_FILE}.$(date +%s).txt" || 
      die "      unable to create archive file" && \
		rm "${TODO_DIR}/notes/${PRE}-${NOTE_FILE}.txt"
    echo "$(getPrefix): Archived note:${NOTE_FILE}"
    ((RETURN+=1)) 
	fi
done

[[ -f "${TODO_TMP_FILE}" ]] && rm -rf "${TODO_TMP_FILE}"

# if we have not archived anything, then report
if [[ -z "${RETURN}" ]]; then
  echo "$(getPrefix): Nothing to archive"
  exit 1
fi