#!/usr/bin/env bash
# shellcheck shell=bash
#===============================================================================
#
#          FILE: notesadd
#
#         USAGE: todo.sh notesadd [ITEMS] [NOTESFILE]
#
#        AUTHOR: Paul Mansfield (paul.mansfield@mansteck.co.uk), 
#     COPYRIGHT: 2009-2021 Paul Mansfield
#       LICENSE: GPL, http://www.gnu.org/copyleft/gpl.html
#===============================================================================

usage () {
	echo "    $(basename "$0") [ITEMS] [NOTESFILE]"
	echo "      add NOTESFILE in ITEMS"
}

# Function to take NOTEFILE and standardize on no note:
_note_fix () {
  INPUT="$1"
  if [[ ${INPUT} =~ 'note:' ]]; then
    NOTE="${INPUT##note:}"
  else
    NOTE="${INPUT}"
  fi
  echo "${NOTE}"
}

# Check notes and archive exist
mkdir -p "${TODO_DIR}/notes/archive" || exit 1
cd "${TODO_DIR}/notes" || exit 1

# Remove action
shift
# Usage for todo.sh help
if [[ "${1}" = "usage" ]] || [[ "${1}" = "-h" ]]; then
	usage
	exit
elif [[ "$#" -lt 2 ]]; then
  echo "      Not enough options"
  usage
  exit 1
fi
# Set notes file from last argument and remove last argument
# this leaves items which we test later
NOTES_FILE="${!#}"
NOTES_FILE=$(_note_fix "${NOTES_FILE}")
set -- "${@:1:$(($#-1))}"
PRE="$(basename "${TODO_FILE}" | sed 's/.txt$//g')"
NOTES=$(find . -maxdepth 1 -name "${PRE}*txt" -printf '%P\n')

# If our notes file is just numbers we didn't get given one
if [[ "${NOTES_FILE}" =~ ^[0-9]+$ ]]; then
  echo "      No notesfile given"
  usage
  exit 1
fi

# Can we edit after addition?
# Only set if file new to todo.txt and note doesn't exist
# Also check we have notesedit addon installed
if [[ "${NOTE_ADD_EDIT}" = "OFF" ]]; then
  if [[ $(grep -c "${NOTES_FILE}" "${TODO_FILE}") -eq 0 ]] && \
    ! [[ -f "${TODOTXT_DIR}/notes/${PRE}-${NOTES}.txt" ]] && \
    [[ $(${TODO_FULL_SH} listaddons | grep -c ^notesedit$) -eq 1 ]]; then
    EDIT_FILE=1
  fi
fi

# Are items in the file?
# shellcheck disable=SC2048
for item in $*; do
  if [[ ${item} -gt $(wc -l "${TODO_FILE}" | cut -f 1 -d " ") ]]; then
    echo "$(getPrefix "${TODO_FILE}"): No task ${item}"
    exit 1
  fi
done

# Use built in append action to add notesfile to each item, testing as we go
# shellcheck disable=SC2048
for item in $*; do
  # Test we have an item number
  if ! [[ "${item}" =~ ^[0-9]+$ ]]; then
    echo "	ITEM is not a number"
    usage
    exit 1
  fi
  "${TODO_FULL_SH}" append "${item}" "note:${NOTES_FILE}"
  echo "$(getPrefix "${TODO_FILE}"): note:${NOTES_FILE} added to item ${item}"
done

# If our tests allow open file for editing
if [[ "${EDIT_FILE}" = 1 ]]; then
  "${TODO_FULL_SH}" notesedit "note:${NOTES_FILE}"
fi