#!/usr/bin/env bash
# shellcheck shell=bash
#===============================================================================
#
#          FILE: notesedit
#
#         USAGE: todo.sh notesedit [NOTESFILE]
#
#        AUTHOR: Paul Mansfield (paul.mansfield@mansteck.co.uk), 
#     COPYRIGHT: 2009-2021 Paul Mansfield
#       LICENSE: GPL, http://www.gnu.org/copyleft/gpl.html
#===============================================================================

usage () {
  echo "    $(basename "$0") [NOTESFILE]"
  echo "      Edit notes file, in \$EDITOR."
  echo "      use listnotes to get list of notes files"
}

# Git add, will error on not in git WD or git not installed 
# so send to dev null
add () {
	if [ -e "${TODOTXT_ACTIONS_DIR}/commit" ]; then
		git add "$1" > /dev/null 2>&1
	fi
}

# Git add, will error on not in gitt WD or git not installed
# so send to dev null
commit () {
	if [ -e "${TODOTXT_ACTIONS_DIR}/commit" ]; then
		git commit "$1" -m "$(date +'%Y-%m-%d %H:%M:%S')" > /dev/null 2>&1
	fi
}

# Function to find editor to use
# Use debian and derivatives editor (auto set by OS)
# If EDITOR already set then use, else if EDITOR not set default to vi
find_editor () {
  if [[ -n ${EDITOR} ]]; then
    true
	elif [[ -L /usr/bin/editor ]]; then
		EDITOR="/usr/bin/editor"
	elif [[ "${EDITOR}x" = "x" ]]; then
		EDITOR="vi"
	fi
  echo "${EDITOR}"
}

# Remove action
shift
# construct file name
# shellcheck disable=2001
NOTE_FILE="$(echo "$1" | sed 's/^note://g')"
PRE="$(basename "${TODO_FILE}" | sed 's/.txt$//g')"
TODO_TMP_FILE="${TODO_TMP_FILE:-${TODO_DIR}/todo.tmp}"

# Tests and show usage
if [[ "${1}" = "usage" ]] || [[ "${1}" = "-h" ]]; then
	usage
	exit
elif [[ -z "${NOTE_FILE}" ]]; then
  echo "    No notes file"
  usage
  exit 1
fi

EDITOR=$(find_editor)

# Create file from todo and 'tickled' files
cat "${TODO_FILE}" > "${TODO_TMP_FILE}"
if [ -n "${TICKLER_DIR}" ]; then
	find "${TICKLER_DIR}" -mindepth 2 -type f -size 1 -exec cat {} \; >>"${TODO_TMP_FILE}"
fi

# If file exists edit it else check lsnotes for pointer then edit 
if [ -e "${TODO_DIR}/notes/${PRE}-${NOTE_FILE}.txt" ]; then
	"${EDITOR}" "${TODO_DIR}/notes/${PRE}-${NOTE_FILE}.txt"
	add "${TODO_DIR}/notes/${PRE}-${NOTE_FILE}.txt"
	commit "${TODO_DIR}/notes/${PRE}-${NOTE_FILE}.txt"
else
	# If note link in todo.txt exists then edit
	# shellcheck disable=SC2046,SC2027,SC2086
	if [ $(grep -oc "\bnote:${NOTE_FILE}\b" "${TODO_TMP_FILE}") -ge 1 ] ;then
		"${EDITOR}" "${TODO_DIR}/notes/${PRE}-${NOTE_FILE}.txt"
		add "${TODO_DIR}/notes/${PRE}-${NOTE_FILE}.txt"
		commit "${TODO_DIR}/notes/${PRE}-${NOTE_FILE}.txt"
    rm -rf "${TODO_TMP_FILE}"
	else
		echo "    No such Notes file, use lsnotes to find notes files"
    usage
    rm -rf "${TODO_TMP_FILE}"
    exit 1
	fi
fi