#!/usr/bin/env bash
# 2011 Paul Mansfield <paul.mansfield@mansteck.co.uk>
# License:    GPL, http://www.gnu.org/copyleft/gpl.html

if [ $1 != "usage" ]; then
    action=$1;shift
fi

usage() {
    echo "  $(basename $0)"
    echo "    List contexts"
    echo ""
}

case $1 in
    "usage")
        usage
    ;;

    "-h")
        usage
    ;;

    *)
        # Create file from todo, done and 'tickled' files
        cat $TODO_FILE $DONE_FILE > $TMP_FILE
        if [ -n $TICKER_DIR ]; then
            find $TICKLER_DIR -mindepth 2 -size 1 -exec cat {} >>$TMP_FILE \;
        fi
        grep -o '\@\w*' "$TMP_FILE" | sort -u
        rm -rf $TMP_FILE
		;;
esac
