#!/bin/bash 
# 2009 Paul Mansfield <paul.mansfield@mansteck.co.uk>
# License:  GPL, http://www.gnu.org/copyleft/gpl.html
if [ $1 != "usage" ]; then
    action=$1;shift
fi

usage (){
  echo "  $(basename $0)"
  echo "    list all possible actions"
  echo ""
}

case $1 in
"usage")
    usage
    exit 0
;;

"-h")
    usage
;;

*)
    ## list all possible actions
    echo `$TODO_FULL_SH -h | grep '^    \w' | grep -v '    command' | awk '{print $1}'| \
    sed 's/|/ /g' ; ls $TODO_ACTIONS_DIR | sort`
;;
esac
