#!/bin/bash
# 2009 Paul Mansfield <paul.mansfield@mansteck.co.uk>
# License:    GPL, http://www.gnu.org/copyleft/gpl.html

if [ $1 != "usage" ]; then
    action=$1;shift
fi

usage() {
    echo "  $(basename $0)"
    echo "    List projects"
    echo ""
}

case $1 in
    "usage")
        usage
    ;;

    "-h")
        usage
    ;;

    *)
        # Create file from todo and 'tickled' files
        cat $TODO_FILE>> $TMP_FILE
        if [ -n $TICKER_DIR ]; then
            find $TICKLER_DIR -mindepth 2 -size 1b -exec cat {} >>$TMP_FILE \;
        fi
        grep -o '\+\w*' "$TMP_FILE" | sort -u | sed 's/^\+//'
		;;
esac
