#!/usr/bin/env bash
# shellcheck shell=bash
#===============================================================================
#
#          FILE: lsprjnopri
#
#         USAGE: todo.sh lsprjnopri
#
#        AUTHOR: Paul Mansfield (paul.mansfield@mansteck.co.uk), 
#     COPYRIGHT: 2009-2021 Paul Mansfield
#       LICENSE: GPL, http://www.gnu.org/copyleft/gpl.html
#===============================================================================

# Functions
usage() {
	echo "  $(basename "$0")"
	echo "    List projects with no priorities set"
	echo ""
}

# Remove action
shift

# Usage for todo.sh help
if [[ "$1" = "usage" ]] || [[ "$1" = "-h" ]]; then
	usage
	exit
fi

# shellcheck disable=SC2034
TODOTXT_VERBOSE=0

# Create array and variable to count hits.
declare -a NOPRI
TOTAL=0
# Find all projects in todo file
PROJECTS=$(${TODO_FULL_SH} listproj | sed 's/^+//g')
for PROJECT in ${PROJECTS} ; do
  # If the project does not have a priority set, add to the array
  if [ "$(grep "${PROJECT}" "${TODO_FILE}" | grep -c "(\w)")" -eq 0 ] ; then
    NOPRI[$TOTAL]=$PROJECT
    TOTAL=$((TOTAL+1))
  fi
done

# Did we find some projects without priorities ?
if [ "${TOTAL}" -gt 0 ] ; then
  for PROJECT in ${NOPRI}; do
    echo "No priority set in ${PROJECT}"
    echo "==============================="
    _list "$TODO_FILE" "+${PROJECT}\b" "" | sed "s/\ \x1b\[[0-9;]*m@[a-zA-Z0-9._:\-]*\b//g"
    echo "====================================="
  done
else
  echo "All projects have priorities set"
fi