#!/usr/bin/env bash
# shellcheck shell=bash
#===============================================================================
#
#          FILE: lsprjnopri
#
#         USAGE: todo.sh lsprjnopri
#
#        AUTHOR: Paul Mansfield (paul.mansfield@mansteck.co.uk), 
#     COPYRIGHT: 2009-2021 Paul Mansfield
#       LICENSE: GPL, http://www.gnu.org/copyleft/gpl.html
#===============================================================================

# Functions
usage() {
	echo "    $(basename "$0")"
	echo "      List projects with no priorities set"
}

die () {
  if [[ -n $* ]]; then
    echo -e "$*"
  fi
	usage
	exit 1
}

# Usage for todo.sh help or remove action
if [[ "${1}" = "usage" ]] || [[ "${2}" = "usage" ]]; then
  usage
  exit
elif [[ "${1}" = "$(basename "$0")" ]]; then
  shift
fi

# Don't run if not projects
if [[ $("${TODO_FULL_SH}" lsprj | wc -l) -eq 0 ]]; then
  die "      No projects in todo.txt"
fi

PROJECTS=$("${TODO_FULL_SH}" lsprj | grep -v '^\(\w\)')
for PROJECT in ${PROJECTS}; do
  PROJECT=${PROJECT/#+/}
  if [ "$(grep "+${PROJECT}" "${TODO_FILE}" | grep -c "(\w)")" -eq 0 ] ; then
    echo "No priority set in ${PROJECT}"
    echo "==============================="
    TODOTXT_VERBOSE=0 _list "$TODO_FILE" "+${PROJECT}\b" "" | \
      sed "s/\ \x1b\[[0-9;]*m@[a-zA-Z0-9._:\-]*\b//g"
    echo "====================================="
    ((NOPRI+=1))
  fi
done

if [[ -z ${NOPRI} ]]; then
  echo "      All projects have priorities set"
fi