#!/usr/bin/env bash
#===============================================================================
#
#          FILE: edit
#
#         USAGE: todo.sh edit [todo|done|cfg] [line number]
#
#        AUTHOR: Paul Mansfield (paul.mansfield@mansteck.co.uk),
#     COPYRIGHT: 2019 Paul Mansfield
#       LICENSE: GPL, http://www.gnu.org/copyleft/gpl.html
#       CREATED: 19/09/09 10:52:44
#===============================================================================

usage() {
  echo "    $(basename "$0") [todo|done|cfg] [line number]"
  echo "      Allows editing of the todo.txt files."
  echo "      todo.txt (todo), done.txt (done) or config (cfg)"
  echo "      files in your default editor or vi"
}

# Find editor to use
find_editor() {
  # If we have EDITOR set at bash or todo.sh config, respect
  if [[ -n "${EDITOR}" ]]; then
    # If we are vim or nvim set variable so we can use line numbers
    if [[ "${EDITOR}" =~ vim ]]; then
      VIM=1
    fi
  # Fall back to editor alternative on debian
  elif [[ -L /usr/bin/editor ]]; then
    EDITOR="/usr/bin/editor"
    # /usr/bin/editor is an alternative, see if its vim
    if [[ "${EDITOR}" = "/usr/bin/editor" ]] && [[ -x "/usr/bin/update-alternatives" ]]; then
      if [[ "$(update-alternatives --query editor | grep ^Value: | grep -c vim)" -eq 1 ]]; then
        VIM=1
      fi
    fi
  # Else set to vim
  elif [[ -z "${EDITOR}" ]]; then
    EDITOR="vim"
    VIM=1
  fi
}

## Variables and tests
# Usage for todo.sh help or remove action
if [[ "${*}" = "usage" ]]; then
  usage
  exit
elif [[ "${1}" = "$(basename "$0")" ]]; then
  shift
fi
# Test for line number
# Number in $1 use and shift out
if [[ "${1}" =~ ^[0-9]+$ ]]; then
  LINE="+${1}"
  shift
# Number in $2 use and leave, only $1 used from here
elif [[ "${2}" =~ ^[0-9]+$ ]]; then
  LINE="+${2}"
# Number is default of +1
else
  LINE="+1"
fi
# Which file. No file then todo.txt is default
if [[ -z "${1}" ]] || [[ "${1}" =~ ^todo$ ]]; then
  EDIT_FILE="${TODO_FILE}"
elif [[ "${1}" =~ ^done$ ]]; then
  EDIT_FILE="${DONE_FILE}"
elif [[ "${1}" =~ ^cfg$ ]]; then
  EDIT_FILE="${TODOTXT_CFG_FILE}"
# Not blank, or a valid file so show usage
else
  usage
  exit 1
fi

## Main
find_editor
# How to edit the file, vim allows +line_number as arg
if [[ "${VIM}" -eq 1 ]]; then
  "${EDITOR}" "$EDIT_FILE" "$LINE"
else
  "${EDITOR}" "$EDIT_FILE"
fi
