#!/usr/bin/env bash
#===============================================================================
#
#          FILE: priupgrade
#
#         USAGE: todo.sh priupgrade [TERM]
#
#        AUTHOR: Paul Mansfield (paul.mansfield@mansteck.co.uk), 
#     COPYRIGHT: 2022 Paul Mansfield
#       LICENSE: GPL, http://www.gnu.org/copyleft/gpl.html
#       CREATED: 14/01/22 10:52:44
#===============================================================================

usage() {
	echo "    $(basename "$0") [TERM]"
	echo "      Increases the priority of all items matching TERM"
  echo "      Without TERM it runs across all priroties"
  echo "      For changes by line number use builtin pri"
}

die () {
	if [[ -n $* ]]; then
		echo -e "$*"
	fi
	usage
	exit 1
}

# Usage for todo.sh help or remove action
if [[ "${1}" = "usage" ]] || [[ "${2}" = "usage" ]]; then
	usage
	exit
elif [[ "${1}" = "$(basename "$0")" ]]; then
  shift
fi

# Gets our items and priorities as builtin pri function takes them i.e. line priority line priority
# shellcheck disable=SC2068
PRIS=$(TODOTXT_PLAIN=1 TODOTXT_VERBOSE=0 "${TODO_FULL_SH}" listpri $@ | grep -v '^x\ ' | awk '{print $1,$2}' | tr 'B-Z' 'A-X' | tr -d '()' | tr '\n' ' ')
# Test if we have found any priorites, error out if none
if [[ -z "${PRIS}" ]]; then
  die "      No priorites in our search of todo.txt"
fi

# Run builtin pri
# shellcheck disable=SC2086
"${TODO_FULL_SH}" pri ${PRIS}