#!/usr/bin/env bash
# origin:
# http://github.com/ginatrapani/todo.txt-cli/blob/addons/.todo.actions.d/adda
# commit: 01a250c702af65b693c8e000ebb5c4f34b2df54f
 
action=$1
shift
 
[ "$action" = "usage" ] && {
  echo "  Add and prioritize A:"
  curcmd=`basename $0`
  echo "    $curcmd \"THING I NEED TO DO +project @context\""
  echo "      Add an item and prioritize it A in one step"
  echo ""
  exit
}
 
if "$TODO_SH" command add "$@"; then
    # figure out the line of what we just added, and prioritize it A
    line=`sed -n '$ =' "$TODO_FILE"`
    echo "$line"
    "$TODO_SH" command pri "$line" A 
fi
