#!/bin/sh
#
# Another 'edit' add-on for todo.sh
# 
# Author: Jon Smajda
# License: GPL, http://www.gnu.org/copyleft/gpl.html
# URL: http://github.com/smajda/todo.actions.d

action=$1
shift

[ "$action" = "usage" ] && {
    echo "  `basename $0` [FILE] [editor arguments]"
    echo "    Open \$TODO_DIR/FILE in \$EDITOR"
    echo "    If left empty, opens $TODO_FILE"
    echo "    Supports vim's +n 'open on line n' feature"
    echo "    See $0"
    echo ""
    exit
}


# if no arguments, open default todo file in EDITOR
if [[ -z "${@}" ]]; then
    "$EDITOR" "$TODO_FILE"
else
    # if argument starts with a "+" open up todo on that line in vi
    if [[ `echo "$@" | grep ^"\+"` ]]; then
        "$EDITOR" "$TODO_FILE" "$@"
        # otherwise, pass all of $@ to vi (separate file and/or line no)
    else
        "$EDITOR" "$TODO_DIR"/"$@"
    fi
fi

exit
