#!/usr/bin/env bash
# shellcheck shell=bash
#===============================================================================
#
#          FILE: projectrename 
#
#         USAGE: todo.sh projectrename [OLD PROJECT] [NEW PROJECT] [ITEM#...]
#
#        AUTHOR: Paul Mansfield (paul.mansfield@mansteck.co.uk), 
#     COPYRIGHT: 2009-2021 Paul Mansfield
#       LICENSE: GPL, http://www.gnu.org/copyleft/gpl.html
#===============================================================================

usage() {
	echo "    $(basename "${0}") [OLD PROJECT] [NEW PROJECT] [ITEM#]"
	echo "      Rename old project to new project in ITEM#"
	echo "      If no ITEM# given the rename all instances of old project"
}

# Function to take PROJECT and standardize
_project_fix () {
  INPUT="$1"
  if [[ ${INPUT} =~ ^\+ ]]; then
    NOTE="${INPUT##+}"
  else
    NOTE="${INPUT}"
  fi
  echo "${NOTE}"
}

# Remove action
shift

# tests
if [[ "${1}" = "usage" ]] || [[ "${1}" = "-h" ]]; then
  usage
  exit
elif [[ $# -lt 2 ]]; then
  echo "   Not enough options"
  usage
  exit 1
fi

OLDPROJECT=$(_project_fix "$1");shift
NEWPROJECT=$(_project_fix "$1");shift
ITEM="$*"

# Check our ITEM# are numeric
if [[ -n "${ITEM}" ]] && ! [[ ${ITEM} =~ ^[0-9\ ]+$ ]]; then
  echo "    ITEM# should be a LINE number"
  usage
  exit 1
fi

# do we have that project in the todofile?
if [[ "$(grep -c "${OLDPROJECT}\>" "${TODO_FILE}")" -eq 0 ]]; then
  echo "    Cannot find project ${OLDPROJECT}"
  usage
  exit 1
fi

# Check OLDPROJECT is found in ITEM#
for item in ${ITEM}; do
  LINE=$(sed -n "${item}p" "${TODO_FILE}")
  if [[ -n "${item}" ]] && ! [[ "${LINE}" =~ \+${OLDPROJECT} ]]; then
    echo "    Cannot find project ${OLDPROJECT} in line number ${ITEM}"
    usage
    exit 1
  fi
done

# Get the ITEM#s to run over
# Either our ITEM or list of items containing OLDPROJECT
if [[ -z "${ITEM}" ]]; then
  ITEM=$(grep -n "${OLDPROJECT}" "${TODO_FILE}" | cut -f1 -d:)
fi

for LINE in ${ITEM}; do
  # Change project on specified lines, do twice once with ending space and once without
  sed -i "{${LINE}s|\ +${OLDPROJECT} |\ +${NEWPROJECT} |;${LINE}s|\ +${OLDPROJECT}$|\ +${NEWPROJECT}|}" "${TODO_FILE}"
  NEWTODO=$(sed -n "${LINE}p" "${TODO_FILE}")
  [ "${TODOTXT_VERBOSE}" -gt 0 ] && {
    echo "${LINE}: ${NEWTODO}"
    echo "$(getPrefix): ${LINE} updated project ${OLDPROJECT} to ${NEWPROJECT}."
  }
done