#!/usr/bin/env bash

#
## Edit the todo.txt files
#

action=$1

function usage() {
    echo "  $(basename $0) [item]"
    echo "    Edit item(s) using text editor."
    echo ""
    exit
}

cmd=${EDITOR:-vi}

case $1 in
    "usage")
        usage
        exit 0
    ;;

    "done")
        $cmd "$DONE_FILE"
    ;;
    
    "report")
        $cmd "$REPORT_FILE"
    ;;

    "todo")
        $cmd "$TODO_FILE"
    ;;
    
    *)
        $cmd "$TODO_FILE"
    ;;

esac
