name: Makefile CI

on:
  push:
    branches: [ feature/fix_ci ]
  pull_request:
    branches: [ feature/fix_ci ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      
    - name: Tests
      run: make test
