name: Makefile CI

on:
  push:
    branches: 
      - develop
      - feature/**
      - release/**
      - master
  pull_request:
    branches:
      - develop
      - feature/**
      - release/**
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      
    - name: Tests
      run: make test
