#!/usr/bin/env bash

action=$1
shift

function usage {
  echo "  Customized upgrade:"
  echo "    upgrade "
  echo "      increases (e.g., B to A) the priority of all previously prioritized items."
  echo ""
  exit
}

[ "$action" = "usage" ] && usage

# Make a backup!
cp "$TODO_FILE" "$TODO_FILE".bak

# Upgrade the items.
awk 'BEGIN { convert="ABCDEFGHIJKLMNOPQRSTUVWXYZ"; } 
    $1~/\([A-Z]\)/ { 
        pri=substr($1,2,1); 
        pos=index(convert,pri)-1; 
        if (pos<0) 
            pos=0; 
        new=substr(convert,pos,1); 
        printf("(%s) ", new); 
        for (i = 2; i <= NF; i++) 
            printf("%s ", $i); 
        printf("\n"); }
    $1!~/\(/ { print; }' "$TODO_FILE".bak > "$TODO_FILE"
